### ISSUE TITLE
3. Random Crash using SDK 2.1.2

### ISSUE THREAD

**Issue by n-ahmad** [Clicktale/android-sdk-demo#3]
java.lang.RuntimeException: Canvas: trying to use a recycled bitmap android.graphics.Bitmap@736b52
	at android.graphics.Canvas.throwIfCannotDraw(Canvas.java:1305)
	at android.graphics.Canvas.drawBitmap(Canvas.java:1392)
	at android.graphics.Bitmap.createBitmap(Bitmap.java:897)
	at android.graphics.Bitmap.createScaledBitmap(Bitmap.java:753)
	at com.clicktale.clicktalesdk.k.a.a(SourceFile:80)
	at com.clicktale.clicktalesdk.h.f.run(SourceFile:59)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:158)
	at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by daviduzan** [comment]
checking

**Comment by daviduzan** [comment]
fixed
